import React from "react";
import Icons from "../Icons";

export const iconsMapping = {
  'iOs': <Icons.Ios />,
  'Vite': <Icons.Vite />,
  'NestJS': <Icons.Nestjs />,
  'Nest.js': <Icons.Nestjs />,
  'Angular': <Icons.Angular />,
  'Swift': <Icons.Swift />,
  'SwiftUI': <Icons.Swift />,
  'ReactJS': <Icons.ReactLogo />,
  'GatsbyJS': <Icons.Gatsby />,
  'Javascript': <Icons.Javascript />,
  'Styled Components': <Icons.Styledcomponents />,
  'Typescript': <Icons.Typescript />,
  'MongoDB': <Icons.Mongodb />,
  'Prisma ORM': <Icons.Prisma />,
  'JWT': <Icons.Jsonwebtokens />,
  'NextJS': <Icons.Nextdotjs />,
  'Next.js': <Icons.Nextdotjs />,
  'Tailwind CSS': <Icons.Tailwindcss />,
  'HTML': <Icons.Html5 />,
  'CSS': <Icons.Css3 />,
  'Node.js': <Icons.Nodedotjs />,
  'MySQL': <Icons.Mysql />,
  'PostgreSQL': <Icons.Postgresql />,
  'AWS': <Icons.Amazonaws />,
  'Azure': <Icons.Azuredevops />,
  'Jest': <Icons.Jest />,
  'Jasmine': <Icons.Jasmine />,
  'Unit testing': <Icons.TestTube />,
  'Jira': <Icons.Jira />,
  'Kanban': <Icons.Kanban />,
  'Scrum': <Icons.Kanban />,
  'Accessibility': <Icons.AccessibilityNew />,
  'ContentfulCMS': <Icons.Contentful />,
  'Git': <Icons.Git />,
  'Sass': <Icons.Sass />,
  'MaterialUI': <Icons.Materialui />,
};